services:
  arklivemap:
    container_name: arklivemap
    hostname: arklivemap
    image: node:lts-alpine
    ports:
      - "127.0.0.1:8088:8080/tcp"
    environment:
      TZ: 'Europe/Vienna'
    restart: unless-stopped
    entrypoint: './entry.sh'
    volumes:
      - './:/home/node'
    working_dir: '/home/node'