version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  arklivemap:
    container_name: arklivemap
    hostname: arklivemap
    image: 18.18.2-alpine
    ports:
      - "127.0.0.1:8088:8080/tcp"
    environment:
      TZ: 'Europe/Vienna'
    restart: unless-stopped
    entrypoint: './entry.sh'
    volumes:
      - './:/home/node'
    working_dir: '/home/node'